export type OnlinePaymentsTestCard = {
  brand: string;
  flow: "Frictionless" | "Challenge" | "Error";
  returnsMethodData: "Y" | "N" | "Not Applicable";
  number: string;
  result: string;
};

export const onlinePaymentsTestCards: OnlinePaymentsTestCard[] = [
  {
    brand: "VISA",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "4200000000000091",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "VISA",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "4200000000000109",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "VISA",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "4200000000000026",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "VISA",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "4200000000000059",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "VISA",
    flow: "Error",
    returnsMethodData: "N",
    number: "4012001037461114",
    result: "Technical Error (no ECI, TransactionStatus=U)",
  },
  {
    brand: "VISA",
    flow: "Error",
    returnsMethodData: "N",
    number: "4012001037141112",
    result:
      "User not enrolled (ECI=06, ECI=01 for Mastercard, TransactionStatus=N)",
  },
  {
    brand: "VISA",
    flow: "Error",
    returnsMethodData: "Not Applicable",
    number: "4532497088771651",
    result: "Card not participating",
  },
  {
    brand: "VISA",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "4200000000000042",
    result: "(determined by challenge)",
  },
  {
    brand: "VISA",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "4200000000000067",
    result: "(determined by challenge)",
  },
  {
    brand: "VISA",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "4200000000000018",
    result: "(determined by challenge)",
  },
  {
    brand: "VISA",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "4200000000000075",
    result: "(determined by challenge)",
  },
  {
    brand: "Mastercard",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "5200000000000007",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "Mastercard",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "5200000000000023",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "Mastercard",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "5200000000000056",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "Mastercard",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "5200000000000106",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "Mastercard",
    flow: "Error",
    returnsMethodData: "N",
    number: "5434580000000006",
    result: "Technical Error (no ECI, TransactionStatus=U)",
  },
  {
    brand: "Mastercard",
    flow: "Error",
    returnsMethodData: "N",
    number: "5457350076543210",
    result:
      "User not enrolled (ECI=06, ECI=01 for Mastercard, TransactionStatus=N)",
  },
  {
    brand: "Mastercard",
    flow: "Error",
    returnsMethodData: "Not Applicable",
    number: "5497260847316287",
    result: "Card not participating",
  },
  {
    brand: "Mastercard",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "5200000000000015",
    result: "(determined by challenge)",
  },
  {
    brand: "Mastercard",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "5200000000000049",
    result: "(determined by challenge)",
  },
  {
    brand: "Mastercard",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "5200000000000064",
    result: "(determined by challenge)",
  },
  {
    brand: "Mastercard",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "5200000000000072",
    result: "(determined by challenge)",
  },
  {
    brand: "MAESTRO",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "6761301000993772",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "MAESTRO",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "6706981111111113",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "MAESTRO",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "6799851000000032",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "MAESTRO",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "6007930123456780",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "MAESTRO",
    flow: "Error",
    returnsMethodData: "N",
    number: "6761301000941201",
    result: "Technical Error (no ECI, TransactionStatus=U)",
  },
  {
    brand: "MAESTRO",
    flow: "Error",
    returnsMethodData: "N",
    number: "6761301000946341",
    result:
      "User not enrolled (ECI=06, ECI=01 for Mastercard, TransactionStatus=N)",
  },
  {
    brand: "MAESTRO",
    flow: "Error",
    returnsMethodData: "Not Applicable",
    number: "6761257707836567",
    result: "Card not participating",
  },
  {
    brand: "MAESTRO",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "6799998900000060018",
    result: "(determined by challenge)",
  },
  {
    brand: "MAESTRO",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "6773670009114879",
    result: "(determined by challenge)",
  },
  {
    brand: "MAESTRO",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "67034200554565015",
    result: "(determined by challenge)",
  },
  {
    brand: "MAESTRO",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "6759888888888888",
    result: "(determined by challenge)",
  },
  {
    brand: "American Express",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "374500262001008",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "American Express",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "377277081382243",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "American Express",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "375987000000062",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "American Express",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "373953192351004",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "American Express",
    flow: "Error",
    returnsMethodData: "N",
    number: "375987000169875",
    result: "Technical Error (no ECI, TransactionStatus=U)",
  },
  {
    brand: "American Express",
    flow: "Error",
    returnsMethodData: "N",
    number: "375987000169883",
    result:
      "User not enrolled (ECI=06, ECI=01 for Mastercard, TransactionStatus=N)",
  },
  {
    brand: "American Express",
    flow: "Error",
    returnsMethodData: "Not Applicable",
    number: "343923092050144",
    result: "Card not participating",
  },
  {
    brand: "American Express",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "343434343434343",
    result: "(determined by challenge)",
  },
  {
    brand: "American Express",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "375987000000021",
    result: "(determined by challenge)",
  },
  {
    brand: "American Express",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "375987000169867",
    result: "(determined by challenge)",
  },
  {
    brand: "American Express",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "371449635398431",
    result: "(determined by challenge)",
  },
  {
    brand: "Diners / Discover",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "36177580677072",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "Diners / Discover",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "6011000400001008",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "Diners / Discover",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "6011010000000003",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "Diners / Discover",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "6011000990099818",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "Diners / Discover",
    flow: "Error",
    returnsMethodData: "N",
    number: "6510000000001248",
    result: "Technical Error (no ECI, TransactionStatus=U)",
  },
  {
    brand: "Diners / Discover",
    flow: "Error",
    returnsMethodData: "N",
    number: "6011025500265831",
    result:
      "User not enrolled (ECI=06, ECI=01 for Mastercard, TransactionStatus=N)",
  },
  {
    brand: "Diners / Discover",
    flow: "Error",
    returnsMethodData: "Not Applicable",
    number: "6011420711746440",
    result: "Card not participating",
  },
  {
    brand: "Diners / Discover",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "36259600000004",
    result: "(determined by challenge)",
  },
  {
    brand: "Diners / Discover",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "6011208701117775",
    result: "(determined by challenge)",
  },
  {
    brand: "Diners / Discover",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "6559906559906557",
    result: "(determined by challenge)",
  },
  {
    brand: "Diners / Discover",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "36458811111119",
    result: "(determined by challenge)",
  },
  {
    brand: "JCB",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "3530111333300000",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "JCB",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "3566002020360505",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "JCB",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "3569990012278361",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "JCB",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "3569990012278353",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "JCB",
    flow: "Error",
    returnsMethodData: "N",
    number: "3566007770017510",
    result: "Technical Error (no ECI, TransactionStatus=U)",
  },
  {
    brand: "JCB",
    flow: "Error",
    returnsMethodData: "N",
    number: "3569990012291497",
    result:
      "User not enrolled (ECI=06, ECI=01 for Mastercard, TransactionStatus=N)",
  },
  {
    brand: "JCB",
    flow: "Error",
    returnsMethodData: "Not Applicable",
    number: "3096023363379943",
    result: "Card not participating",
  },
  {
    brand: "JCB",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "3566002345432153",
    result: "(determined by challenge)",
  },
  {
    brand: "JCB",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "3569990010095916",
    result: "(determined by challenge)",
  },
  {
    brand: "JCB",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "3569990012300876",
    result: "(determined by challenge)",
  },
  {
    brand: "JCB",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "3569990012300884",
    result: "(determined by challenge)",
  },
  {
    brand: "Cashlink Malta",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "58873111111111115",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "Cashlink Malta",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "58873111111111123",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "Cashlink Malta",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "58873111111111131",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "Cashlink Malta",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "58873111111111149",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "Cashlink Malta",
    flow: "Error",
    returnsMethodData: "N",
    number: "58873111111111156",
    result: "Technical Error (no ECI, TransactionStatus=U)",
  },
  {
    brand: "Cashlink Malta",
    flow: "Error",
    returnsMethodData: "N",
    number: "58873111111111164",
    result:
      "User not enrolled (ECI=06, ECI=01 for Mastercard, TransactionStatus=N)",
  },
  {
    brand: "Cashlink Malta",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "58873111111111172",
    result: "(determined by challenge)",
  },
  {
    brand: "Cashlink Malta",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "58873111111111180",
    result: "(determined by challenge)",
  },
  {
    brand: "Cashlink Malta",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "58873111111111222",
    result: "(determined by challenge)",
  },
  {
    brand: "Cashlink Malta",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "58873111111111230",
    result: "(determined by challenge)",
  },
  {
    brand: "Dankort",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "5019995420853334",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "Dankort",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "5019999531137108",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "Dankort",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "5019991658672173",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "Dankort",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "5019991503655373",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "Dankort",
    flow: "Error",
    returnsMethodData: "N",
    number: "5019996890729079",
    result: "Technical Error (no ECI, TransactionStatus=U)",
  },
  {
    brand: "Dankort",
    flow: "Error",
    returnsMethodData: "N",
    number: "4571995700667571",
    result:
      "User not enrolled (ECI=06, ECI=01 for Mastercard, TransactionStatus=N)",
  },
  {
    brand: "Dankort",
    flow: "Error",
    returnsMethodData: "Not Applicable",
    number: "4571993314926574",
    result: "Card not participating",
  },
  {
    brand: "Dankort",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "4571991262718985",
    result: "(determined by challenge)",
  },
  {
    brand: "Dankort",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "4571995712628447",
    result: "(determined by challenge)",
  },
  {
    brand: "Dankort",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "4571998470279619",
    result: "(determined by challenge)",
  },
  {
    brand: "Dankort",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "5019991707044788",
    result: "(determined by challenge)",
  },
  {
    brand: "Carte Bancaire",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "4561402725337522",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "Carte Bancaire",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "4561404340834677",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "Carte Bancaire",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "4561402252349452",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "Carte Bancaire",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "4561403505852789",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "Carte Bancaire",
    flow: "Error",
    returnsMethodData: "N",
    number: "5132838291362666",
    result: "Technical Error (no ECI, TransactionStatus=U)",
  },
  {
    brand: "Carte Bancaire",
    flow: "Error",
    returnsMethodData: "N",
    number: "5132836684345470",
    result:
      "User not enrolled (ECI=06, ECI=01 for Mastercard, TransactionStatus=N)",
  },
  {
    brand: "Carte Bancaire",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "5132831842334250",
    result: "(determined by challenge)",
  },
  {
    brand: "Carte Bancaire",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "4976077311101836",
    result: "(determined by challenge)",
  },
  {
    brand: "Carte Bancaire",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "4976075309982316",
    result: "(determined by challenge)",
  },
  {
    brand: "UnionPay",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "6250947000000014",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "UnionPay",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "6250947000000022",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "UnionPay",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "6250947000000089",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "UnionPay",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "6250944220914108",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "UnionPay",
    flow: "Error",
    returnsMethodData: "N",
    number: "6250947000000048",
    result: "Technical Error (no ECI, TransactionStatus=U)",
  },
  {
    brand: "UnionPay",
    flow: "Error",
    returnsMethodData: "N",
    number: "6250947000000030",
    result:
      "User not enrolled (ECI=06, ECI=01 for Mastercard, TransactionStatus=N)",
  },
  {
    brand: "UnionPay",
    flow: "Error",
    returnsMethodData: "Not Applicable",
    number: "6250947000000052",
    result: "Card not participating",
  },
  {
    brand: "UnionPay",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "6250947000000097",
    result: "(determined by challenge)",
  },
  {
    brand: "UnionPay",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "6250944196725207",
    result: "(determined by challenge)",
  },
  {
    brand: "UnionPay",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "6250949644050173",
    result: "(determined by challenge)",
  },
  {
    brand: "UnionPay",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "6250945882768112",
    result: "(determined by challenge)",
  },
  {
    brand: "Bancontact Link",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "6703997212737146",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "Bancontact Link",
    flow: "Frictionless",
    returnsMethodData: "Y",
    number: "6703993351560670",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "Bancontact Link",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "6703994942941098",
    result:
      "Successful frictionless authentication (ECI=05, ECI=02 for Mastercard, TransactionStatus=Y)",
  },
  {
    brand: "Bancontact Link",
    flow: "Frictionless",
    returnsMethodData: "N",
    number: "6703991694504181",
    result: "Attempt (ECI=06, ECI=01 for Mastercard, TransactionStatus=A)",
  },
  {
    brand: "Bancontact Link",
    flow: "Error",
    returnsMethodData: "N",
    number: "6703995730382544",
    result: "Technical Error (no ECI, TransactionStatus=U)",
  },
  {
    brand: "Bancontact Link",
    flow: "Error",
    returnsMethodData: "N",
    number: "6703649519767306",
    result:
      "User not enrolled (ECI=06, ECI=01 for Mastercard, TransactionStatus=N)",
  },
  {
    brand: "Bancontact Link",
    flow: "Error",
    returnsMethodData: "Not Applicable",
    number: "6703649519767555",
    result: "Card not participating",
  },
  {
    brand: "Bancontact Link",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "6703646173211993",
    result: "(determined by challenge)",
  },
  {
    brand: "Bancontact Link",
    flow: "Challenge",
    returnsMethodData: "Y",
    number: "6703647823718742",
    result: "(determined by challenge)",
  },
  {
    brand: "Bancontact Link",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "6703618847851199",
    result: "(determined by challenge)",
  },
  {
    brand: "Bancontact Link",
    flow: "Challenge",
    returnsMethodData: "N",
    number: "6703618084221908",
    result: "(determined by challenge)",
  },
];
