import {
  Accessibility,
  Account,
  Accounting,
  ActivateCard,
  Active,
  Add,
  AddEmployees,
  AddItems,
  Alarm,
  Alelo,
  Alert,
  AlternativePaymentMethod,
  AmericanExpress,
  Apm,
  ApplePay,
  Apps,
  Archive,
  Area,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowSlanted,
  ArrowUp,
  Article,
  Atm,
  Attachment,
  AutomaticBalanceTransfer,
  BancoEstado,
  Bancontact,
  Bank,
  Barcode,
  Basket,
  Battery,
  BatteryAlert,
  Bitcoin,
  Blik,
  Bluetooth,
  Boleto,
  Briefcase,
  BrowserSecure,
  Cafe,
  Calendar,
  Callback,
  Camera,
  CardIn,
  CardOut,
  CardReaderAir,
  CardReaderSolo,
  CardReaderSoloLite,
  CardSecurity,
  CardUnknown,
  Cash,
  CashAdvance,
  CashStack,
  Challenge,
  Checkmark,
  Checkout,
  Cheque,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Close,
  Clothing,
  ColorCorrection,
  ColorInversion,
  Company,
  Conecs,
  Confirm,
  ContactPicker,
  Cookie,
  CookiePreferences,
  Copy,
  CreditNote,
  Crop,
  CustomAmount,
  Customize,
  Dankort,
  Delete,
  DeliveryNote,
  DinersClub,
  DirectDebit,
  Discount,
  Discover,
  Download,
  DownloadCloud,
  Drag,
  DriverLicense,
  Ec,
  Edit,
  Eftpos,
  ElectronicInvoice,
  Elo,
  Elv,
  Email,
  EmailChat,
  Employees,
  Eps,
  Expenses,
  ExternalLink,
  Facebook,
  FacebookMessenger,
  FasterPayments,
  Favorite,
  FeeCalculator,
  FeesSummary,
  File,
  Filter,
  FilterApplied,
  FlashOff,
  FlashOn,
  Flashlight,
  FlipCamera,
  Freeze,
  Gauge,
  GeneralSettings,
  GiftCard,
  Giropay,
  Globe,
  GooglePay,
  Grid,
  HamburgerMenu,
  Health,
  Help,
  Hide,
  Hiper,
  Hipercard,
  History,
  Home,
  Hospitality,
  Id,
  Ideal,
  Image,
  Info,
  Instagram,
  Insurance,
  InterestOnBalance,
  Inventory,
  Invoice,
  Items,
  Jcb,
  Key,
  Klarna,
  Language,
  Laptop,
  Legal,
  Like,
  Link,
  Linkedin,
  List,
  LiveChat,
  Location,
  Login,
  Logout,
  Loja,
  Maestro,
  Manage,
  Mastercard,
  Mcc,
  MealVoucher,
  Messenger,
  Minus,
  MobilePhone,
  Moon,
  More,
  MoreCircle,
  Mybank,
  Nfc,
  NfcPayment,
  NoCosts,
  NoSim,
  NotificationCenter,
  Notify,
  NotifyCircle,
  OnlinePayments,
  OnlineStore,
  Orders,
  Package,
  PaidOut,
  ParcelLocker,
  Passport,
  Pause,
  Paused,
  PayPal,
  PaymentLink,
  PaymentMethods,
  PayoutSettings,
  Payouts,
  Percentage,
  Phone,
  PhoneChat,
  Pinterest,
  Pix,
  PixFull,
  Play,
  Plus,
  PostFinance,
  PrintFailed,
  Printer,
  Profile,
  Promote,
  Przelewy24,
  QrCode,
  Random,
  Receipt,
  ReceiptAttached,
  ReceiptMissing,
  ReceiptSmart,
  ReceiptUnreviewed,
  RecurringInvoice,
  RedCompra,
  Refer,
  ReferAFriend,
  Refresh,
  Refunded,
  Remove,
  Reports,
  ResidencePermit,
  Reward,
  Sales,
  SamsungPay,
  Satispay,
  Search,
  Secure,
  SecurePayments,
  SelectAll,
  Send,
  Sepa,
  Services,
  Settings,
  Share,
  Shop,
  SimCard,
  Sodexo,
  Sofort,
  Sort,
  Sparkles,
  Stop,
  Stopped,
  StoreEditor,
  SumUpCard,
  SumUpConnect,
  SumUpLogo,
  SumUpLogomark,
  Sun,
  Support,
  Swile,
  Tablet,
  TapToPay,
  Taxes,
  ThumbDown,
  ThumbUp,
  Ticket,
  Time,
  Tipping,
  Transactions,
  TransferIn,
  TransferOut,
  Transit,
  Truck,
  Twitter,
  Unfavorite,
  UnionPay,
  Upgrade,
  Upload,
  UploadCloud,
  View,
  VirtualTerminal,
  Visa,
  VisaElectron,
  Volume,
  Vpay,
  Vr,
  Webspace,
  WhatsApp,
  Wifi,
  WireTransfer,
  Youtube,
  ZipFile,
} from "@sumup-oss/icons";

export const Icons = {
  accessibility: Accessibility,
  account: Account,
  accounting: Accounting,
  activate_card: ActivateCard,
  active: Active,
  add: Add,
  add_employees: AddEmployees,
  add_items: AddItems,
  alarm: Alarm,
  alelo: Alelo,
  alert: Alert,
  alternative_payment_method: AlternativePaymentMethod,
  american_express: AmericanExpress,
  apm: Apm,
  apple_pay: ApplePay,
  apps: Apps,
  archive: Archive,
  area: Area,
  arrow_down: ArrowDown,
  arrow_left: ArrowLeft,
  arrow_right: ArrowRight,
  arrow_slanted: ArrowSlanted,
  arrow_up: ArrowUp,
  article: Article,
  atm: Atm,
  attachment: Attachment,
  automatic_balance_transfer: AutomaticBalanceTransfer,
  banco_estado: BancoEstado,
  bancontact: Bancontact,
  bank: Bank,
  barcode: Barcode,
  basket: Basket,
  battery: Battery,
  battery_alert: BatteryAlert,
  bitcoin: Bitcoin,
  blik: Blik,
  bluetooth: Bluetooth,
  boleto: Boleto,
  briefcase: Briefcase,
  browser_secure: BrowserSecure,
  cafe: Cafe,
  calendar: Calendar,
  callback: Callback,
  camera: Camera,
  card_in: CardIn,
  card_out: CardOut,
  card_reader_air: CardReaderAir,
  card_reader_solo: CardReaderSolo,
  card_reader_solo_lite: CardReaderSoloLite,
  card_security: CardSecurity,
  card_unknown: CardUnknown,
  cash: Cash,
  cash_advance: CashAdvance,
  cash_stack: CashStack,
  challenge: Challenge,
  checkmark: Checkmark,
  checkout: Checkout,
  cheque: Cheque,
  chevron_down: ChevronDown,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  chevron_up: ChevronUp,
  close: Close,
  clothing: Clothing,
  color_correction: ColorCorrection,
  color_inversion: ColorInversion,
  company: Company,
  conecs: Conecs,
  confirm: Confirm,
  contact_picker: ContactPicker,
  cookie: Cookie,
  cookie_preferences: CookiePreferences,
  copy: Copy,
  credit_note: CreditNote,
  crop: Crop,
  custom_amount: CustomAmount,
  customize: Customize,
  dankort: Dankort,
  delete: Delete,
  delivery_note: DeliveryNote,
  diners_club: DinersClub,
  direct_debit: DirectDebit,
  discount: Discount,
  discover: Discover,
  download: Download,
  download_cloud: DownloadCloud,
  drag: Drag,
  driver_license: DriverLicense,
  ec: Ec,
  edit: Edit,
  eftpos: Eftpos,
  electronic_invoice: ElectronicInvoice,
  elo: Elo,
  elv: Elv,
  email: Email,
  email_chat: EmailChat,
  employees: Employees,
  eps: Eps,
  expenses: Expenses,
  external_link: ExternalLink,
  facebook: Facebook,
  facebook_messenger: FacebookMessenger,
  faster_payments: FasterPayments,
  favorite: Favorite,
  fee_calculator: FeeCalculator,
  fees_summary: FeesSummary,
  file: File,
  filter: Filter,
  filter_applied: FilterApplied,
  flash_off: FlashOff,
  flash_on: FlashOn,
  flashlight: Flashlight,
  flip_camera: FlipCamera,
  freeze: Freeze,
  gauge: Gauge,
  general_settings: GeneralSettings,
  gift_card: GiftCard,
  giropay: Giropay,
  globe: Globe,
  google_pay: GooglePay,
  grid: Grid,
  hamburger_menu: HamburgerMenu,
  health: Health,
  help: Help,
  hide: Hide,
  hiper: Hiper,
  hipercard: Hipercard,
  history: History,
  home: Home,
  hospitality: Hospitality,
  id: Id,
  ideal: Ideal,
  image: Image,
  info: Info,
  instagram: Instagram,
  insurance: Insurance,
  interest_on_balance: InterestOnBalance,
  inventory: Inventory,
  invoice: Invoice,
  items: Items,
  jcb: Jcb,
  key: Key,
  klarna: Klarna,
  language: Language,
  laptop: Laptop,
  legal: Legal,
  like: Like,
  link: Link,
  linkedin: Linkedin,
  list: List,
  live_chat: LiveChat,
  location: Location,
  login: Login,
  logout: Logout,
  loja: Loja,
  maestro: Maestro,
  manage: Manage,
  mastercard: Mastercard,
  mcc: Mcc,
  meal_voucher: MealVoucher,
  messenger: Messenger,
  minus: Minus,
  mobile_phone: MobilePhone,
  moon: Moon,
  more: More,
  more_circle: MoreCircle,
  mybank: Mybank,
  nfc: Nfc,
  nfc_payment: NfcPayment,
  no_costs: NoCosts,
  no_sim: NoSim,
  notification_center: NotificationCenter,
  notify: Notify,
  notify_circle: NotifyCircle,
  online_payments: OnlinePayments,
  online_store: OnlineStore,
  orders: Orders,
  package: Package,
  paid_out: PaidOut,
  parcel_locker: ParcelLocker,
  passport: Passport,
  pause: Pause,
  paused: Paused,
  pay_pal: PayPal,
  payment_link: PaymentLink,
  payment_methods: PaymentMethods,
  payout_settings: PayoutSettings,
  payouts: Payouts,
  percentage: Percentage,
  phone: Phone,
  phone_chat: PhoneChat,
  pinterest: Pinterest,
  pix: Pix,
  pix_full: PixFull,
  play: Play,
  plus: Plus,
  post_finance: PostFinance,
  print_failed: PrintFailed,
  printer: Printer,
  profile: Profile,
  promote: Promote,
  przelewy24: Przelewy24,
  qr_code: QrCode,
  random: Random,
  receipt: Receipt,
  receipt_attached: ReceiptAttached,
  receipt_missing: ReceiptMissing,
  receipt_smart: ReceiptSmart,
  receipt_unreviewed: ReceiptUnreviewed,
  recurring_invoice: RecurringInvoice,
  red_compra: RedCompra,
  refer: Refer,
  refer_a_friend: ReferAFriend,
  refresh: Refresh,
  refunded: Refunded,
  remove: Remove,
  reports: Reports,
  residence_permit: ResidencePermit,
  reward: Reward,
  sales: Sales,
  samsung_pay: SamsungPay,
  satispay: Satispay,
  search: Search,
  secure: Secure,
  secure_payments: SecurePayments,
  select_all: SelectAll,
  send: Send,
  sepa: Sepa,
  services: Services,
  settings: Settings,
  share: Share,
  shop: Shop,
  sim_card: SimCard,
  sodexo: Sodexo,
  sofort: Sofort,
  sort: Sort,
  sparkles: Sparkles,
  stop: Stop,
  stopped: Stopped,
  store_editor: StoreEditor,
  sum_up_card: SumUpCard,
  sum_up_connect: SumUpConnect,
  sum_up_logo: SumUpLogo,
  sum_up_logomark: SumUpLogomark,
  sun: Sun,
  support: Support,
  swile: Swile,
  tablet: Tablet,
  tap_to_pay: TapToPay,
  taxes: Taxes,
  thumb_down: ThumbDown,
  thumb_up: ThumbUp,
  ticket: Ticket,
  time: Time,
  tipping: Tipping,
  transactions: Transactions,
  transfer_in: TransferIn,
  transfer_out: TransferOut,
  transit: Transit,
  truck: Truck,
  twitter: Twitter,
  unfavorite: Unfavorite,
  union_pay: UnionPay,
  upgrade: Upgrade,
  upload: Upload,
  upload_cloud: UploadCloud,
  view: View,
  virtual_terminal: VirtualTerminal,
  visa: Visa,
  visa_electron: VisaElectron,
  volume: Volume,
  vpay: Vpay,
  vr: Vr,
  webspace: Webspace,
  whats_app: WhatsApp,
  wifi: Wifi,
  wire_transfer: WireTransfer,
  youtube: Youtube,
  zip_file: ZipFile,
};
