name: Github Actions

on:
  pull_request:
    paths:
      - ".github/**"

defaults:
  run:
    working-directory: ./.github

permissions:
  contents: read

jobs:
  actionlint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          sparse-checkout: |
            .github
      - uses: reviewdog/action-actionlint@741f06346b1784e277fcc9bd907cf39c7d31e443
        with:
          filter_mode: nofilter
          fail_on_error: true
          reporter: github-pr-check
