name: Github Actions

on:
  pull_request:
    paths:
      - ".github/**"

defaults:
  run:
    working-directory: ./.github

permissions:
  contents: read

jobs:
  actionlint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          sparse-checkout: |
            .github
      - uses: reviewdog/action-actionlint@664c8ef5435569dd2880e62d891ab3ecdf98dc60
        with:
          filter_mode: nofilter
          fail_on_error: true
          reporter: github-pr-check
