name: CI

on:
  push:
    branches: [main]
  merge_group:
  pull_request:
    branches: [main]

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: "--max_old_space_size=4096"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: npm run tsc

      - name: Run Check
        run: npm run check

      - name: Run linter
        run: npm run lint

      # Tests do not exist at the moment
      # - name: Build
      #   # build beforehand so resolution of static assets that are build during the build
      #   # process works
      #   run: |
      #     # Filling in env with placeholders for the build to pass
      #     cp .env.test .env
      #     npm run build
