name: CI

on:
  push:
    branches: [main]
  merge_group:
  pull_request:
    branches: [main]

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: "--max_old_space_size=4096"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Setup Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Check
        run: npm run check

      - name: Run linter
        run: npm run lint

      # TODO: Enable once links are fixed
      # - name: Run build
      #   run: npm run build
      #   env:
      #     CHECK_LINKS: true
