name: CI

on:
  push:
    branches: [main]
  merge_group:
  pull_request:
    branches: [main]

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_OPTIONS: "--max_old_space_size=4096"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Run rumdl
        uses: rvben/rumdl@98bf311e3711c41180c5acd306f283eddb8fe137 # v0.1.37
        with:
          version: 0.1.35
          path: "."
          fail-on-error: true

      - name: Install dependencies
        run: npm ci

      - name: Run Check
        run: npm run check

      - name: Run linter
        run: npm run lint

      - name: Run linkcheck
        run: npm run linkcheck
