name: Environments - Stage

on:
  schedule:
    # Every day from Monday to Friday at 6am UTC
    - cron: "0 6 * * 1-5"
  workflow_dispatch:

jobs:
  sync-stage:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: connor-baer/action-sync-branch@v1.1.0
        with:
          branch: stage
          token: ${{ secrets.GITHUB_TOKEN }}
          force: true
